{% set name = "bullet" %}
{% set version = "2.2.0" %}

package:
  name: "{{ name|lower }}-python"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: dfa0fa81810ad1a9e688815ca04f24af87ff5cdbe803b42fa634b1f50fc9d887

build:
  noarch: python
  number: 8
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - setuptools >=42
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python ={{ python_min }}
  imports:
    - bullet

about:
  home: "https://github.com/bchao1/bullet"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Beautiful Python prompts made simple."
  dev_url: https://github.com/bchao1/bullet

extra:
  recipe-maintainers:
    - mxr-conda
    - RyanHackney
    - rluria14
    - ndmaxar
